[package]
name = "lemon-graph"
description = "Modular library for running directed computation graphs."
keywords = ["graph", "computation"]
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
