name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      ollama:
        image: ollama/ollama
        ports:
          - 11434:11434
      qdrant:
        image: qdrant/qdrant
        env:
          QDRANT__SERVICE__GRPC_PORT: 6334
        ports:
          - 6333:6333
          - 6334:6334
    steps:
      - uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          remove-dotnet: "true"
          remove-haskell: "true"

      - uses: actions/checkout@v4
        with:
          submodules: "true"
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: DeterminateSystems/flake-checker-action@v7

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: Swatinem/rust-cache@v2

      - run: nix develop -c cargo clippy --fix --no-deps
      - run: nix develop -c cargo fmt --all
      - run: nix develop -c prettier -w .
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: lint"
          default_author: github_actions

      - run: nix develop -c nix run .#generate-readme
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: generate README"
          default_author: github_actions

      - run: nix develop -c cargo doc --all-features --no-deps
      - run: nix develop -c cargo test --all-features --all-targets
      - run: nix develop -c cargo test --doc --all-features
